# 01 — SpaceX API : collecte des lancements Falcon 9

**Objectif :** reconstruire la collecte à partir de la [SpaceX REST API v4](https://github.com/r-spacex/SpaceX-API). Ce notebook interroge les données accessibles au moment de l’exécution : elles peuvent différer du jeu historique IBM (90 lancements). Les tableaux et chiffres affichés ne sont valides **qu’après exécution**.

In [1]:
import requests
import pandas as pd
from pathlib import Path
from datetime import datetime, timezone

pd.set_option("display.max_columns", 30)
OUT = Path("data") if Path("data").exists() else Path("../data")
OUT.mkdir(parents=True, exist_ok=True)
BASE = "https://api.spacexdata.com/v4"

def get_json(endpoint):
    response = requests.get(f"{BASE}/{endpoint}", timeout=40)
    response.raise_for_status()
    return response.json()

In [7]:
url = (
    "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/"
    "IBM-DS0321EN-SkillsNetwork/datasets/API_call_spacex_api.json"
)

response = requests.get(url, timeout=30)
response.raise_for_status()

data = pd.json_normalize(response.json())

print("Nombre de lancements :", len(data))
print("Nombre de colonnes :", len(data.columns))

display(data.head())

Nombre de lancements : 107
Nombre de colonnes : 42

,static_fire_date_utc,static_fire_date_unix,tbd,net,window,rocket,success,details,crew,ships,capsules,payloads,launchpad,auto_update,failures,...,fairings.ships,links.patch.small,links.patch.large,links.reddit.campaign,links.reddit.launch,links.reddit.media,links.reddit.recovery,links.flickr.small,links.flickr.original,links.presskit,links.webcast,links.youtube_id,links.article,links.wikipedia,fairings
0,2006-03-17T00:00:00.000Z,1.142554e+09,False,False,0.0,5e9d0d95eda69955f709d1eb,False,Engine failure at 33 seconds and loss of vehicle,[],[],[],[5eb0e4b5b6c3bb0006eeb1e1],5e9e4502f5090995de566f86,True,"[{'time': 33, 'altitude': None, 'reason': 'mer...",...,[],https://images2.imgbox.com/3c/0e/T8iJcSN3_o.png,https://images2.imgbox.com/40/e3/GypSkayF_o.png,None,None,None,None,[],[],None,https://www.youtube.com/watch?v=0a_00nJ_Y88,0a_00nJ_Y88,https://www.space.com/2196-spacex-inaugural-fa...,https://en.wikipedia.org/wiki/DemoSat,NaN
1,None,NaN,False,False,0.0,5e9d0d95eda69955f709d1eb,False,Successful first stage burn and transition to ...,[],[],[],[5eb0e4b6b6c3bb0006eeb1e2],5e9e4502f5090995de566f86,True,"[{'time': 301, 'altitude': 289, 'reason': 'har...",...,[],https://images2.imgbox.com/4f/e3/I0lkuJ2e_o.png,https://images2.imgbox.com/be/e7/iNqsqVYM_o.png,None,None,None,None,[],[],None,https://www.youtube.com/watch?v=Lk4zQ2wP-Nc,Lk4zQ2wP-Nc,https://www.space.com/3590-spacex-falcon-1-roc...,https://en.wikipedia.org/wiki/DemoSat,NaN
2,None,NaN,False,False,0.0,5e9d0d95eda69955f709d1eb,False,Residual stage 1 thrust led to collision betwe...,[],[],[],"[5eb0e4b6b6c3bb0006eeb1e3, 5eb0e4b6b6c3bb0006e...",5e9e4502f5090995de566f86,True,"[{'time': 140, 'altitude': 35, 'reason': 'resi...",...,[],https://images2.imgbox.com/3d/86/cnu0pan8_o.png,https://images2.imgbox.com/4b/bd/d8UxLh4q_o.png,None,None,None,None,[],[],None,https://www.youtube.com/watch?v=v0w9p3U8860,v0w9p3U8860,http://www.spacex.com/news/2013/02/11/falcon-1...,https://en.wikipedia.org/wiki/Trailblazer_(sat...,NaN
3,2008-09-20T00:00:00.000Z,1.221869e+09,False,False,0.0,5e9d0d95eda69955f709d1eb,True,Ratsat was carried to orbit on the first succe...,[],[],[],[5eb0e4b7b6c3bb0006eeb1e5],5e9e4502f5090995de566f86,True,[],...,[],https://images2.imgbox.com/e9/c9/T8CfiSYb_o.png,https://images2.imgbox.com/e0/a7/FNjvKlXW_o.png,None,None,None,None,[],[],None,https://www.youtube.com/watch?v=dLQ2tZEH6G0,dLQ2tZEH6G0,https://en.wikipedia.org/wiki/Ratsat,https://en.wikipedia.org/wiki/Ratsat,NaN
4,None,NaN,False,False,0.0,5e9d0d95eda69955f709d1eb,True,None,[],[],[],[5eb0e4b7b6c3bb0006eeb1e6],5e9e4502f5090995de566f86,True,[],...,[],https://images2.imgbox.com/a7/ba/NBZSw3Ho_o.png,https://images2.imgbox.com/8d/fc/0qdZMWWx_o.png,None,None,None,None,[],[],http://www.spacex.com/press/2012/12/19/spacexs...,https://www.youtube.com/watch?v=yTaIDooc8Og,yTaIDooc8Og,http://www.spacex.com/news/2013/02/12/falcon-1...,https://en.wikipedia.org/wiki/RazakSAT,NaN

In [9]:
# Vérifier que les données IBM ont été chargées
print("Dimensions initiales :", data.shape)

# Sélectionner uniquement les lancements Falcon 9
falcon9_id = "5e9d0d95eda69973a809d1ec"

data_falcon9 = data[
    data["rocket"] == falcon9_id
].copy()

data_falcon9.reset_index(drop=True, inplace=True)

print("Nombre de lancements Falcon 9 :", len(data_falcon9))

display(data_falcon9.head())

Dimensions initiales : (107, 42)
Nombre de lancements Falcon 9 : 99

,static_fire_date_utc,static_fire_date_unix,tbd,net,window,rocket,success,details,crew,ships,capsules,payloads,launchpad,auto_update,failures,...,fairings.ships,links.patch.small,links.patch.large,links.reddit.campaign,links.reddit.launch,links.reddit.media,links.reddit.recovery,links.flickr.small,links.flickr.original,links.presskit,links.webcast,links.youtube_id,links.article,links.wikipedia,fairings
0,2010-03-13T00:00:00.000Z,1.268438e+09,False,False,0.0,5e9d0d95eda69973a809d1ec,True,None,[],[],[],[5eb0e4b7b6c3bb0006eeb1e7],5e9e4501f509094ba4566f84,True,[],...,[],https://images2.imgbox.com/5c/36/gbDKf6Y7_o.png,https://images2.imgbox.com/d6/12/yxne8mMD_o.png,None,None,None,None,[],[],http://forum.nasaspaceflight.com/index.php?act...,https://www.youtube.com/watch?v=nxSxgBKlYws,nxSxgBKlYws,http://www.spacex.com/news/2013/02/12/falcon-9...,https://en.wikipedia.org/wiki/Dragon_Spacecraf...,NaN
1,2010-12-04T00:00:00.000Z,1.291421e+09,False,False,0.0,5e9d0d95eda69973a809d1ec,True,None,[],[5ea6ed2d080df4000697c901],[5e9e2c5bf35918ed873b2664],"[5eb0e4b9b6c3bb0006eeb1e8, 5eb0e4b9b6c3bb0006e...",5e9e4501f509094ba4566f84,True,[],...,NaN,https://images2.imgbox.com/d9/3e/FfrN88ry_o.png,https://images2.imgbox.com/00/2f/FhtEd0nB_o.png,None,None,None,None,[],[],http://www.spacex.com/files/downloads/cots1-20...,https://www.youtube.com/watch?v=cdLITgWKe_0,cdLITgWKe_0,https://en.wikipedia.org/wiki/SpaceX_COTS_Demo...,https://en.wikipedia.org/wiki/SpaceX_COTS_Demo...,NaN
2,2012-04-30T00:00:00.000Z,1.335744e+09,False,False,0.0,5e9d0d95eda69973a809d1ec,True,"Launch was scrubbed on first attempt, second l...",[],[5ea6ed2d080df4000697c901],[5e9e2c5bf3591882af3b2665],[5eb0e4bab6c3bb0006eeb1ea],5e9e4501f509094ba4566f84,True,[],...,NaN,https://images2.imgbox.com/fc/7a/r9ITwL12_o.png,https://images2.imgbox.com/2b/8e/MYyHbnd2_o.png,None,None,None,None,[],[],https://www.nasa.gov/pdf/649910main_cots2_pres...,https://www.youtube.com/watch?v=tpQzDbAY7yI,tpQzDbAY7yI,https://en.wikipedia.org/wiki/Dragon_C2%2B,https://en.wikipedia.org/wiki/Dragon_C2%2B,NaN
3,2012-09-29T00:00:00.000Z,1.348877e+09,False,False,0.0,5e9d0d95eda69973a809d1ec,True,"CRS-1 successful, but the secondary payload wa...",[],[5ea6ed2d080df4000697c902],[5e9e2c5bf3591835983b2666],"[5eb0e4bab6c3bb0006eeb1eb, 5eb0e4bab6c3bb0006e...",5e9e4501f509094ba4566f84,True,[],...,NaN,https://images2.imgbox.com/0b/33/2eLGEejP_o.png,https://images2.imgbox.com/52/09/eNvilptL_o.png,None,None,None,None,[],[],https://www.nasa.gov/pdf/694166main_SpaceXCRS-...,https://www.youtube.com/watch?v=-Vk3hiV_zXU,-Vk3hiV_zXU,https://www.nasa.gov/mission_pages/station/mai...,https://en.wikipedia.org/wiki/SpaceX_CRS-1,NaN
4,2013-02-25T18:30:00.000Z,1.361817e+09,False,False,0.0,5e9d0d95eda69973a809d1ec,True,Last launch of the original Falcon 9 v1.0 laun...,[],[5ea6ed2d080df4000697c902],[5e9e2c5bf359189ef23b2667],[5eb0e4bbb6c3bb0006eeb1ed],5e9e4501f509094ba4566f84,True,[],...,NaN,https://images2.imgbox.com/1b/b6/Z4oktZeR_o.png,https://images2.imgbox.com/ef/39/FyZRYeOh_o.png,None,https://www.reddit.com/r/space/comments/19gm5f...,None,None,[],[],https://www.nasa.gov/sites/default/files/files...,https://www.youtube.com/watch?v=ik0ElKl5kW4,ik0ElKl5kW4,https://en.wikipedia.org/wiki/SpaceX_CRS-2,https://en.wikipedia.org/wiki/SpaceX_CRS-2,NaN

In [5]:
print("Dimensions :", df.shape)
display(df.isna().sum().rename("Missing values").to_frame())
print("Atterrissage indiqué :", df["LandingSuccess"].value_counts(dropna=False).to_dict())

NameError: name 'df' is not defined

In [10]:

# ============================================================
# IBM DATA SCIENCE CAPSTONE - SPACEX FALCON 9
# NOTEBOOK 1 : DATA COLLECTION USING SPACEX API DATA
# ============================================================

import requests
import pandas as pd
import numpy as np
from datetime import datetime, timezone
from IPython.display import display

# ------------------------------------------------------------
# 1. LOAD HISTORICAL SPACEX API DATA FROM IBM
# ------------------------------------------------------------

url = (
    "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/"
    "IBM-DS0321EN-SkillsNetwork/datasets/API_call_spacex_api.json"
)

response = requests.get(url, timeout=60)
response.raise_for_status()

data = pd.json_normalize(response.json())

print("Original dataset shape:", data.shape)
display(data.head())

# ------------------------------------------------------------
# 2. FILTER FALCON 9 LAUNCHES
# ------------------------------------------------------------

falcon9_id = "5e9d0d95eda69973a809d1ec"

data_falcon9 = data[
    data["rocket"] == falcon9_id
].copy()

data_falcon9.reset_index(drop=True, inplace=True)

print("Falcon 9 launches:", len(data_falcon9))

# ------------------------------------------------------------
# 3. LOAD IBM ENRICHED FALCON 9 DATASET
# ------------------------------------------------------------

csv_url = (
    "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/"
    "IBM-DS0321EN-SkillsNetwork/datasets/dataset_part_1.csv"
)

df = pd.read_csv(csv_url)

print("Dataset shape:", df.shape)
print("Columns:", df.columns.tolist())

display(df.head(10))

# ------------------------------------------------------------
# 4. CHECK MISSING VALUES
# ------------------------------------------------------------

missing = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (
        df.isnull().mean() * 100
    ).round(2)
})

display(missing)

# ------------------------------------------------------------
# 5. CHECK DATA TYPES
# ------------------------------------------------------------

print("Data types:")
print(df.dtypes)

# ------------------------------------------------------------
# 6. DESCRIPTIVE STATISTICS
# ------------------------------------------------------------

display(df.describe(include="all").T)

# ------------------------------------------------------------
# 7. EXPLORE LAUNCH SITES
# ------------------------------------------------------------

print("Launches by site:")
display(df["LaunchSite"].value_counts())

# ------------------------------------------------------------
# 8. EXPLORE ORBITS
# ------------------------------------------------------------

print("Launches by orbit:")
display(df["Orbit"].value_counts())

# ------------------------------------------------------------
# 9. EXPLORE LANDING OUTCOMES
# ------------------------------------------------------------

print("Landing outcomes:")
display(df["Outcome"].value_counts(dropna=False))

# ------------------------------------------------------------
# 10. CHECK LANDING PAD MISSING VALUES
# ------------------------------------------------------------

print(
    "Missing LandingPad values:",
    df["LandingPad"].isnull().sum()
)

# ------------------------------------------------------------
# 11. SAVE COLLECTED DATA
# ------------------------------------------------------------

df.to_csv("dataset_part_1.csv", index=False)

print("File saved: dataset_part_1.csv")

# ------------------------------------------------------------
# 12. DOWNLOAD DATASET IN GOOGLE COLAB
# ------------------------------------------------------------

from google.colab import files

files.download("dataset_part_1.csv")

# ------------------------------------------------------------
# 13. FINAL SUMMARY
# ------------------------------------------------------------

print("\n========== DATA COLLECTION SUMMARY ==========")
print("Collection date:", datetime.now(timezone.utc))
print("Original API records:", len(data))
print("Falcon 9 API records:", len(data_falcon9))
print("Enriched dataset records:", len(df))
print("Total columns:", len(df.columns))
print("Unique launch sites:", df["LaunchSite"].nunique())
print("Unique orbit types:", df["Orbit"].nunique())
print("=============================================")
print("NOTEBOOK 1 COMPLETED")

Original dataset shape: (107, 42)

,static_fire_date_utc,static_fire_date_unix,tbd,net,window,rocket,success,details,crew,ships,capsules,payloads,launchpad,auto_update,failures,...,fairings.ships,links.patch.small,links.patch.large,links.reddit.campaign,links.reddit.launch,links.reddit.media,links.reddit.recovery,links.flickr.small,links.flickr.original,links.presskit,links.webcast,links.youtube_id,links.article,links.wikipedia,fairings
0,2006-03-17T00:00:00.000Z,1.142554e+09,False,False,0.0,5e9d0d95eda69955f709d1eb,False,Engine failure at 33 seconds and loss of vehicle,[],[],[],[5eb0e4b5b6c3bb0006eeb1e1],5e9e4502f5090995de566f86,True,"[{'time': 33, 'altitude': None, 'reason': 'mer...",...,[],https://images2.imgbox.com/3c/0e/T8iJcSN3_o.png,https://images2.imgbox.com/40/e3/GypSkayF_o.png,None,None,None,None,[],[],None,https://www.youtube.com/watch?v=0a_00nJ_Y88,0a_00nJ_Y88,https://www.space.com/2196-spacex-inaugural-fa...,https://en.wikipedia.org/wiki/DemoSat,NaN
1,None,NaN,False,False,0.0,5e9d0d95eda69955f709d1eb,False,Successful first stage burn and transition to ...,[],[],[],[5eb0e4b6b6c3bb0006eeb1e2],5e9e4502f5090995de566f86,True,"[{'time': 301, 'altitude': 289, 'reason': 'har...",...,[],https://images2.imgbox.com/4f/e3/I0lkuJ2e_o.png,https://images2.imgbox.com/be/e7/iNqsqVYM_o.png,None,None,None,None,[],[],None,https://www.youtube.com/watch?v=Lk4zQ2wP-Nc,Lk4zQ2wP-Nc,https://www.space.com/3590-spacex-falcon-1-roc...,https://en.wikipedia.org/wiki/DemoSat,NaN
2,None,NaN,False,False,0.0,5e9d0d95eda69955f709d1eb,False,Residual stage 1 thrust led to collision betwe...,[],[],[],"[5eb0e4b6b6c3bb0006eeb1e3, 5eb0e4b6b6c3bb0006e...",5e9e4502f5090995de566f86,True,"[{'time': 140, 'altitude': 35, 'reason': 'resi...",...,[],https://images2.imgbox.com/3d/86/cnu0pan8_o.png,https://images2.imgbox.com/4b/bd/d8UxLh4q_o.png,None,None,None,None,[],[],None,https://www.youtube.com/watch?v=v0w9p3U8860,v0w9p3U8860,http://www.spacex.com/news/2013/02/11/falcon-1...,https://en.wikipedia.org/wiki/Trailblazer_(sat...,NaN
3,2008-09-20T00:00:00.000Z,1.221869e+09,False,False,0.0,5e9d0d95eda69955f709d1eb,True,Ratsat was carried to orbit on the first succe...,[],[],[],[5eb0e4b7b6c3bb0006eeb1e5],5e9e4502f5090995de566f86,True,[],...,[],https://images2.imgbox.com/e9/c9/T8CfiSYb_o.png,https://images2.imgbox.com/e0/a7/FNjvKlXW_o.png,None,None,None,None,[],[],None,https://www.youtube.com/watch?v=dLQ2tZEH6G0,dLQ2tZEH6G0,https://en.wikipedia.org/wiki/Ratsat,https://en.wikipedia.org/wiki/Ratsat,NaN
4,None,NaN,False,False,0.0,5e9d0d95eda69955f709d1eb,True,None,[],[],[],[5eb0e4b7b6c3bb0006eeb1e6],5e9e4502f5090995de566f86,True,[],...,[],https://images2.imgbox.com/a7/ba/NBZSw3Ho_o.png,https://images2.imgbox.com/8d/fc/0qdZMWWx_o.png,None,None,None,None,[],[],http://www.spacex.com/press/2012/12/19/spacexs...,https://www.youtube.com/watch?v=yTaIDooc8Og,yTaIDooc8Og,http://www.spacex.com/news/2013/02/12/falcon-1...,https://en.wikipedia.org/wiki/RazakSAT,NaN

Falcon 9 launches: 99
Dataset shape: (90, 17)
Columns: ['FlightNumber', 'Date', 'BoosterVersion', 'PayloadMass', 'Orbit', 'LaunchSite', 'Outcome', 'Flights', 'GridFins', 'Reused', 'Legs', 'LandingPad', 'Block', 'ReusedCount', 'Serial', 'Longitude', 'Latitude']

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
0,1,2010-06-04,Falcon 9,6104.959412,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0003,-80.577366,28.561857
1,2,2012-05-22,Falcon 9,525.000000,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0005,-80.577366,28.561857
2,3,2013-03-01,Falcon 9,677.000000,ISS,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0007,-80.577366,28.561857
3,4,2013-09-29,Falcon 9,500.000000,PO,VAFB SLC 4E,False Ocean,1,False,False,False,NaN,1.0,0,B1003,-120.610829,34.632093
4,5,2013-12-03,Falcon 9,3170.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1004,-80.577366,28.561857
5,6,2014-01-06,Falcon 9,3325.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1005,-80.577366,28.561857
6,7,2014-04-18,Falcon 9,2296.000000,ISS,CCAFS SLC 40,True Ocean,1,False,False,True,NaN,1.0,0,B1006,-80.577366,28.561857
7,8,2014-07-14,Falcon 9,1316.000000,LEO,CCAFS SLC 40,True Ocean,1,False,False,True,NaN,1.0,0,B1007,-80.577366,28.561857
8,9,2014-08-05,Falcon 9,4535.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1008,-80.577366,28.561857
9,10,2014-09-07,Falcon 9,4428.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1011,-80.577366,28.561857

                Missing_Count  Missing_Percentage
FlightNumber                0                0.00
Date                        0                0.00
BoosterVersion              0                0.00
PayloadMass                 0                0.00
Orbit                       0                0.00
LaunchSite                  0                0.00
Outcome                     0                0.00
Flights                     0                0.00
GridFins                    0                0.00
Reused                      0                0.00
Legs                        0                0.00
LandingPad                 26               28.89
Block                       0                0.00
ReusedCount                 0                0.00
Serial                      0                0.00
Longitude                   0                0.00
Latitude                    0                0.00

Data types:
FlightNumber        int64
Date               object
BoosterVersion     object
PayloadMass       float64
Orbit              object
LaunchSite         object
Outcome            object
Flights             int64
GridFins             bool
Reused               bool
Legs                 bool
LandingPad         object
Block             float64
ReusedCount         int64
Serial             object
Longitude         float64
Latitude          float64
dtype: object

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
FlightNumber,90.0,NaN,NaN,NaN,45.5,26.124701,1.0,23.25,45.5,67.75,90.0
Date,90,90,2010-06-04,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BoosterVersion,90,1,Falcon 9,90,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PayloadMass,90.0,NaN,NaN,NaN,6104.959412,4694.67172,350.0,2510.75,4701.5,8912.75,15600.0
Orbit,90,11,GTO,27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LaunchSite,90,3,CCAFS SLC 40,55,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Outcome,90,8,True ASDS,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Flights,90.0,NaN,NaN,NaN,1.788889,1.213172,1.0,1.0,1.0,2.0,6.0
GridFins,90,2,True,70,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Reused,90,2,False,53,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Legs,90,2,True,71,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LandingPad,64,5,5e9e3032383ecb6bb234e7ca,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Block,90.0,NaN,NaN,NaN,3.5,1.595288,1.0,2.0,4.0,5.0,5.0
ReusedCount,90.0,NaN,NaN,NaN,1.655556,1.710254,0.0,0.0,1.0,3.0,5.0
Serial,90,53,B1049,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Longitude,90.0,NaN,NaN,NaN,-86.366477,14.149518,-120.610829,-80.603956,-80.577366,-80.577366,-80.577366
Latitude,90.0,NaN,NaN,NaN,29.449963,2.141306,28.561857,28.561857,28.561857,28.608058,34.632093

Launches by site:

LaunchSite
CCAFS SLC 40    55
KSC LC 39A      22
VAFB SLC 4E     13
Name: count, dtype: int64

Launches by orbit:

Orbit
GTO      27
ISS      21
VLEO     14
PO        9
LEO       7
SSO       5
MEO       3
HEO       1
ES-L1     1
SO        1
GEO       1
Name: count, dtype: int64

Landing outcomes:

Outcome
True ASDS      41
None None      19
True RTLS      14
False ASDS      6
True Ocean      5
False Ocean     2
None ASDS       2
False RTLS      1
Name: count, dtype: int64

Missing LandingPad values: 26
File saved: dataset_part_1.csv

========== DATA COLLECTION SUMMARY ==========
Collection date: 2026-10-29 22:06:33.356406+00:00
Original API records: 107
Falcon 9 API records: 99
Enriched dataset records: 90
Total columns: 17
Unique launch sites: 3
Unique orbit types: 11
=============================================
NOTEBOOK 1 COMPLETED

## Interprétation à rédiger après exécution
- Combien de lancements Falcon 9 sont présents dans **cette extraction** ?
- Combien de valeurs manquent dans `LandingSuccess` et `LandingPad` ?
- **Attention :** `Success` indique la réussite du lancement/de la mission, et **non** celle de l’atterrissage du premier étage.
- Pour retrouver les valeurs exactes du quiz IBM, employer les **datasets historiques du cours**, plutôt que les données live.